### ISSUE TITLE
The ddraw.dll file makes BL TPS unable to launch.

### ISSUE THREAD

**Issue by AvoidAtAllCosts** [c0dycode/BorderlandsPluginLoader#1]
I'm using both the autoexec and Borderlands Commander plugins for TPS (UHD) and I noticed that whenever I have the ddraw.dll file in the win32 folder, the game doesn't launch. A console window will show up with the text "Created Console!", then the console window will close and nothing happens. I'm using the same plugins for BL2 and without any problems (there's still a console window running in the background but the game itself will also launch.

**Comment by c0dycode** [comment]
Ooops. Forgot to remove the DebugConsole from the Autoexec build. I've updated those. :) See if it works then

**Comment by AvoidAtAllCosts** [comment]
Yes, it works again. And the console window is gone. Thank you!
