### ISSUE TITLE
Borderlands 2 wont start up when ddraw.dll is in its folder

### ISSUE THREAD

**Issue by lAmadeusl** [c0dycode/BorderlandsPluginLoader#3]
I also cant seem to find the "autoexec" thing that was in the other TPS issue.

**Comment by c0dycode** [comment]
If the game won't launch, then you need to update the Plugins that you use.
So either
https://github.com/c0dycode/BL-CommandInjector
or
https://github.com/c0dycode/BL-AutoexecDLL

But that issue not related to the PluginLoader.
