### ISSUE TITLE
Borderlands TPS fails to load with ddraw.dll installed

### ISSUE THREAD

**Issue by RobertVorback** [c0dycode/BorderlandsPluginLoader#5]
After the Feb 27 2020 game update, the game will not start
with ddraw.dll in the ~\BorderlandsPreSequel\Binaries\Win32\
folder. I have been using it with Borderlands Commander without
issues up until the Feb update. I have removed the file and can now
launch the game. Will there be a fix for this at some point?
Thanks for any help you can give

**Comment by c0dycode** [comment]
This will be caused by an outdated [CommandInjector](https://github.com/c0dycode/BL-CommandInjector). I haven't looked into it yet and I'm not too sure if I actually will do so.

There is an alternative here though: https://github.com/bl-sdk/PythonSDK

**Comment by RobertVorback** [comment]
Thank you for your quick reply, PythonSdk looks very interesting
I will look into it
